/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ChatResponse {
  currentUserId?: string;
  id?: string;
  lastMessage?: string;
  lastMessageTime?: string;
  name?: string;
  otherUserId?: string;
  recipientOnline?: boolean;
  unreadCount?: number;
}
